<div id="nav-type"></div>
<br /><br />
<div class="textbox">
    <img src="assets/images/gamedev_splash.png" style="width: 100%" /> <br />
    <h1>Que tipo de jogo eu deveria fazer?</h1>
    <div class="text-separator"></div>
    <br /><br />
    Todos nós queremos fazer o maior jogo e o mais impressionante que qualquer um ja viu antes. Queremos mostrar o jogo e receber admiração dos outros. Queremos fazer algo que mereça reconhecimento. Nós queremos fazer logo de cara o jogo dos sonhos e que todo mundo vai se impressionar pelo quão incrível nós somos. Não. Não faça isso como seu primeiro jogo. <br /><br />
    Se você quer fazer o jogo dos seu sonhos, é como se você quisesse derrotar o chefe final no seu primeiro level. Você precisa subir de nível com os pequenos inimigos primeiro, para entender como funciona. Você precisa entender que tipo de desenvolvedor você é. Você precisa aprender quais tipos de jogos você gosta de fazer e não de jogar. Você precisa achar o seu estilo e juntar o seu nicho no mundo do desenvolvimento. Todos nós temos uma vocação e fazendo coisas pequenas vai te ajudar a encontrar a sua. <br /><br />
    Isso também não significa que você tem que infelizmente ter que só passar pelos tutoriais e milhares de projetos que nunca vão ver a luz do dia. Significa que você terá que fazer algo pequeno com a intenção de lançar e receber feedbacks, comentários e opiniões para que você possa evoluir. Jogar algumas sessões de RPG Dungeons e Dragons e mestrar algumas campanhas com um mundinho que você criou. Faça um jogo arcade, publique ele, e veja como que o público reage a ele. Entre em Game Jams e sinta como é trabalhar com outros desenvolvedores como um time. Melhore sempre para que possa fazer jogos incríveis. <br /><br />
    Uma das melhores maneiras de começar esse processo é montando um <a href="https://docs.google.com/document/d/1Vl7BMvzUOhbunJrI_X1gUc6x-LAp3aaBiPwHUf27B70" target="_blank" rel="noopener noreferrer" >GDD, ou Game Design Document</a>. Esse documento é a bíblia do projeto que vai ajudar a organizar o projeto inteiro e manter dentro do escopo. Também ajuda a escolher qual a melhor engine e/ou linguagem que pode funcionar para o seu projeto antes de você se dedicar a ele. Em geral um GDD poupa tempo e dinheiro no desenvolvimento o que é sempre benefico. <br /><br />
    Mesmo com toda a nossa experiência anterior ainda temos dificuldades em lançar jogos de forma indie. Sempre trabalhamos para uma empresa. Nunca lançamos uma demo ou construímos uma comunidade. Mas estamos fazendo pequenos projetos, que faz nosso trabalho melhor. Outras experiências também ajudam no desenvolvimento. Parte do que aprendemos nas empresas de jogos facilita nos processos e erros já cometidos para que não se repita nos proximos jogos. E esse processo de aprendizado e melhoria tem que fazer parte de tudo que fazemos, pois nenhuma experiência é desperdiçada, não só para você, mas também para quem trabalha com você.
</div>
<br /><br />